- BEF/.gitignore
- BEF/build.gradle
- BEF/src/main/java/com/example/BEF/BefApplication.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/OpenAIClient.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/OpenAIClientConfig.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/OpenAIClientService.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/TranscriptionRequest.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/WhisperController.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/WhisperTranscriptionRequest.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/WhisperTranscriptionResponse.java
- BEF/src/main/resources/application.properties
수정사항 : Build.gradle 의존성 추가, application.properties파일 삭제, gitignore수정 BefApplication에 feign 클라이언트 등록을 위해 어노테이션 추가
추가사항 : OpenAi의 whisper-1 모델을 통해 음성 파일을 텍스트로 변경하는 코드 추가. -> 추후 검색 기능을 위한 핵심 키워드 추출기능 업데이트 예정
파일 설명
- OpenAIClient.java : OpenFeign과 OpenAI API와의 통신을 위해 인터페이스생성
- OpenAIClientService.java : Client 인테페이스를 사용하여 실질적인 API 호출 수행
- OpenAIClientConfig.java : APIkey, 호출 모델 등을 설정
- WhisperController.java : api/transcription의 해당하는 엔드포인트를 통해 오디오 파일을 TranscriptionRequest 객체로 변환 후 Open AI 서비스에 전달
- TranscriptionRequest.java : 오디오 파일을 Whisper API로 전송 될 요청 객체
- WhisperTranscriptionRequest.java : Whisper API에 전송될 데이터를 정의
- WhisperTranscriptionResponse.java : 텍스트 변환 결과를 담는 응답 객체
참고 자료:
https://eastshine12.tistory.com/59
> 음성 텍스트변환 기능

- BEF/.gitignore
- BEF/build.gradle
- BEF/src/main/java/com/example/BEF/Area/Domain/Area.java
- BEF/src/main/java/com/example/BEF/Area/Service/AreaRepository.java
- BEF/src/main/java/com/example/BEF/DataSetting/Controller/DataSettingController.java
- BEF/src/main/java/com/example/BEF/DataSetting/Service/SettingAreaService.java
- BEF/src/main/java/com/example/BEF/DataSetting/Service/SettingLocationService.java
- BEF/src/main/java/com/example/BEF/Location/Domain/Location.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationRepository.java
- Domain 추가
- Repository 추가 및 area_code로 area를 리턴하는 함수 추가
- Domain 추가
- Repository 추가
/data/area
OpenApi에서 제공하는 [지역코드조회] 오퍼레이션을 호출해 지역 관련 정보 저장
/data/location
OpenApi에서 제공하는 [지역기반관광정보조회], [공통정보조회] 오퍼레이션을 호출해 관광지 관련 정보 저장
- settingAreaData
1. URL을 통해 지역코드조회 api를 호출한 후 json 형태의 response를 파싱
2. insertAreasIntoDB 호출
- insertAreasIntoDB
DB에 실질적으로 정보를 insert하는 함수
- settingLocationData
1. URL을 통해 지역기반관광정보조회 api를 호출한 후 json 형태의 response를 파싱
2. 각 장소의 contentId를 통해 공통정보조회 api를 호출해 개요, (전화번호) 정보를 파싱
3. Location에 필요 정보를 setting 해준 후 saveAll()을 통해 DB에 반영
> Open API 데이터 DB Insert - Area, Location

- BEF/build.gradle
- BEF/src/main/java/com/example/BEF/MapLocation/Controller/MapLocationController.java
- BEF/src/main/java/com/example/BEF/MapLocation/DTO/MapLocationRequest.java
- BEF/src/main/java/com/example/BEF/MapLocation/DTO/MapLocationResponse.java
- BEF/src/main/java/com/example/BEF/MapLocation/Repository/MapLocationRepository.java
- BEF/src/main/java/com/example/BEF/MapLocation/Service/MapLocationService.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/Client/OpenAIClient.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/Config/OpenAIClientConfig.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/Controller/WhisperController.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/DTO/TranscriptionRequest.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/DTO/WhisperTranscriptionRequest.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/DTO/WhisperTranscriptionResponse.java
- BEF/src/main/java/com/example/BEF/VoiceSearch/Service/OpenAIClientService.java
---
Client,Config,Controller,DTO,Service 패키지로 나누어 정리했다.
---
- Repository
위도와 경도 값을 받아 하버사인 공식을 통해 구면적거리 반경 10Km 안에 있는 장소를 검색하여 제공한다.
- Service
Repository에서 검색한 값을 List 형태로 저장한다.
- DTO
요청값(gpsX,gpsY), 응답값(관광지 이름, 주소, gpsX, gpsY, 원본이미지, 썸네일이미지) 객체로 저장한다.
- Controller
GET,/api/map?gpsX={gpsX}&gpsY={gpsY}
ex)/api/map?gpsX=127.0495222&gpsY=37.66583333
해당 URI를 통해 위도와 경도를 요청하면 위치 반경 10Km 안에 있는 응답값들을 리스트 형식으로 리턴해준다.
> 음성인식검색파일정리, 10Km 주변 장소 검색기능

- BEF/src/main/java/com/example/BEF/User/Controller/UserController.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinReq.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinRes.java
- BEF/src/main/java/com/example/BEF/User/Domain/User.java
- BEF/src/main/java/com/example/BEF/User/Service/UserRepository.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
{
"userName" : "normalUser", // 유저명(String)
"gender" : "woman", // 성별(String)
"age" : "20", // 나이(Long)
"senior" : "false", // 노약자(Boolean)
"wheelchair" : "false", // 휠체어(Boolean)
"blindHandicap" : "false", // 시각 장애(Boolean)
"hearingHandicap" : "false", // 청각 장애(Boolean)
"infantsFamily" : "false" // 영유아(Boolean)
}
{
"userNumber": 15, // 유저 번호(Long)
"userName": "normalUser" // 유저명(String)
}
> 온보딩 정보 입력 받기 API

- BEF/src/main/java/com/example/BEF/Disabled/Service/DisabledService.java
- BEF/src/main/java/com/example/BEF/Location/Controller/LocationController.java
- BEF/src/main/java/com/example/BEF/Location/DTO/LocationInfoRes.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationRepository.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationService.java
**주소(구) 기준으로 addr에서 검색해서 필터링 후 리스트로 리턴**
- district(지역 구, String)
- 장소 정보
- 장애 관련 정보
> 지역(구) 기반 관광지 리스트 검색

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseInfoRes.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseLocRes.java
- BEF/src/main/java/com/example/BEF/Course/Domain/Course.java
- BEF/src/main/java/com/example/BEF/Course/Domain/UserCourse.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseRepository.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
- BEF/src/main/java/com/example/BEF/Course/Service/UserCourseRepository.java
- BEF/src/main/java/com/example/BEF/Disabled/Domain/Disabled.java
- BEF/src/main/java/com/example/BEF/Location/Domain/Location.java
- BEF/src/main/java/com/example/BEF/User/Domain/User.java
유저 번호, 코스 이름 
-> 코스 리스트 생성
유저 번호, 코스 번호
-> 코스 리스트 삭제 및 해당 코스에 속한 모든 유저 코스 정보 삭제
코스 번호, 관광지 ID-> 해당 코스에 관광지 추가, 유저 코스 정보 생성
코스 번호, 관광지 ID-> 유저 코스 정보 삭제
유저 번호 -> 해당 유저의 코스 목록 리턴(코스 번호, 코스 이름)
> 코스 관련 API - 코스 리스트 생성 및 삭제, 코스에 장소 추가 및 삭제, 코스 목록 조회

- BEF/src/main/java/com/example/BEF/Location/Controller/LocationController.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationService.java
destrict -> state(시), city(구, 군)
구, 군이 전체 -> 시로만 검색하게 !
> 지역구 검색 - state, city

- BEF/src/main/java/com/example/BEF/WebConfig/WebConfig.java
> webconfig localhost 수정

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/Domain/UserCourse.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseRepository.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
관광지 저장 버튼 클릭시 저장 리스트에 저장할 수 있도록
유저 회원가입시 저장 리스트를 개별로 생성해 해당 리스트에 담기도록 했음.
유저 번호를 기반으로 저장 리스트를 가져와 해당 리스트 내 관광지 목록 리턴
코스 번호 기반으로 코스 리스트 가져와 해당 코스 내 관광지 목록 리턴
> 코스 관련 API 추가: 관광지 저장, 저장한 관광지 목록 조회, 코스 관광지 목록 조회 API 추가

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseInfoRes.java
- BEF/src/main/java/com/example/BEF/Course/Domain/Course.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
- BEF/src/main/java/com/example/BEF/Location/DTO/UserLocationRes.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
> 코스 생성, 관광지 목록 조회 API 수정

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseAddReq.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseLocRes.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseSaveRes.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
> 코스에 장소 추가 API 수정

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseLocationRes.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
- 코스 번호, 코스명, 코스 설명 추가
- 장애 정보 리스트 추가
> 코스 리스트 내 관광지 조회 API 수정

- BEF/src/main/java/com/example/BEF/DetailedInformation/DetailedInformationController.java
- BEF/src/main/java/com/example/BEF/DetailedInformation/DetailedInformationResponse.java
- BEF/src/main/java/com/example/BEF/DetailedInformation/DetailedInformationService.java
> 관광지 상세정보조회 기능 응답값 description 추가

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/SaveLocationReq.java
- BEF/src/main/java/com/example/BEF/Course/Domain/Course.java
- BEF/src/main/java/com/example/BEF/Location/Controller/LocationController.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationService.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinReq.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinRes.java
- BEF/src/main/java/com/example/BEF/User/Domain/User.java
- BEF/src/main/java/com/example/BEF/User/Service/UserRepository.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
아래 기술한 API에 사용되는 DTO, 로직 내 userNumber를 uuid로 수정했습니다.
- 회원가입 API
- 코스 생성 api
- 코스 삭제 api 
- 나의 코스 목록 조회 api
-  관광지 저장 api
-  저장한 관광지 조회 api
- 유저 맞춤 관광지 리스트 api
> Refactor/UUID : 프로젝트 내 userNumber -> uuid 수정

- BEF/src/main/java/com/example/BEF/User/Controller/UserController.java
- BEF/src/main/java/com/example/BEF/User/Service/UserRepository.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
UserRepository 내 existsByUuid를 통해 유저 확인 여부를 리턴합니다.
> feat: 유저 존재 여부 확인 API

- BEF/src/main/java/com/example/BEF/Config/WebConfig.java
- BEF/src/main/java/com/example/BEF/User/Controller/UserController.java
리턴 타입을 Boolean으로 수정하고, WebConfig 파일을 수정했습니다.
> feat: 유저 존재 여부 확인 API 수정 및 WebConfig 수정

- BEF/src/main/java/com/example/BEF/Data/Controller/DataController.java
- BEF/src/main/java/com/example/BEF/Data/Service/SettingAreaService.java
- BEF/src/main/java/com/example/BEF/Data/Service/SettingLocationService.java
- BEF/src/main/java/com/example/BEF/Util/JsonParsingUtil.java
음식점 데이터의 content_type_id도 다루기 위해 기존의 setLocations() 수정했습니다.
추가로 중복 코드를 JsonParsingUtil 클래스로 분리해 사용합니다.
또한, 기존의 URL 생성시 문자열을 그대로 사용하는 방식이 아닌 변수화해 사용하는 방식으로 수정합니다.
> feat: 음식점 데이터 저장 API 구현 및 프로젝트 구조 수정

- BEF/build.gradle
- BEF/src/main/java/com/example/BEF/tts/config/OpenAIConfig.java
- BEF/src/main/java/com/example/BEF/tts/controller/TTSController.java
- BEF/src/main/java/com/example/BEF/tts/dto/Message.java
- BEF/src/main/java/com/example/BEF/tts/dto/TextMessage.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/Content.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/ImageContent.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/ImageMessage.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/ImageUrl.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/TTSRequest.java
- BEF/src/main/java/com/example/BEF/tts/dto/request/TextContent.java
- BEF/src/main/java/com/example/BEF/tts/dto/response/Choice.java
- BEF/src/main/java/com/example/BEF/tts/dto/response/TTSResponse.java
- BEF/src/main/java/com/example/BEF/tts/service/TTSService.java
<br>OpenAI api를 통하여 캡처된 화면 이미지의 대한 설명을 텍스트로 반환하는 기능을 구현하였습니다.<br>
<br>OpenAI api 적용을 위한 설정 파일과 이미지를 요청값으로 보내기 위한 인코딩 과정 텍스트에대한 응답값, 해당 API를 위한 컨트롤러 및 서비스를 구현하였습니다. Swagger를 통해 API 테스트를 할 수 있습니다.<br>
<br>build 파일에 QueryDsl 관련 설정을 추가하였습니다. <br>
> [feat] TTS 구현

- BEF/src/main/java/com/example/BEF/Course/DTO/UserCourseRes.java
- BEF/src/main/java/com/example/BEF/Course/Domain/Course.java
- BEF/src/main/java/com/example/BEF/Course/Domain/Saved.java
- BEF/src/main/java/com/example/BEF/Course/Domain/UserCourse.java
- BEF/src/main/java/com/example/BEF/Course/Repository/CourseRepository.java
- BEF/src/main/java/com/example/BEF/Course/Repository/SavedRepository.java
- BEF/src/main/java/com/example/BEF/Course/Repository/UserCourseRepository.java
- BEF/src/main/java/com/example/BEF/Disability/Disability.java
- BEF/src/main/java/com/example/BEF/Disability/DisabilityEntity.java
- BEF/src/main/java/com/example/BEF/Disability/DisabilityRepository.java
- BEF/src/main/java/com/example/BEF/Disability/UserDisability.java
- BEF/src/main/java/com/example/BEF/Disability/UserDisabilityRepository.java
- BEF/src/main/java/com/example/BEF/Location/Service/LocationService.java
- BEF/src/main/java/com/example/BEF/TripType/TripType.java
- BEF/src/main/java/com/example/BEF/TripType/TripTypeEntity.java
- BEF/src/main/java/com/example/BEF/TripType/TripTypeRepository.java
- BEF/src/main/java/com/example/BEF/TripType/UserTripType.java
- BEF/src/main/java/com/example/BEF/TripType/UserTripTypeRepository.java
- BEF/src/main/java/com/example/BEF/User/Controller/UserController.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserDisabledDTO.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinReq.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinRes.java
- BEF/src/main/java/com/example/BEF/User/Domain/User.java
- BEF/src/main/java/com/example/BEF/User/Service/UserRepository.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
- User 및 관련 도메인(TripType, Disability 등) 생성 및 수정
- 유저 생성 API 수정
- 유저 조회 API 수정
- 유저 코스 조회 API 수정
> [Refact/user] 유저 관련 API 수정

- BEF/src/main/java/com/example/BEF/Search/Repository/SearchRepository.java
<br>현재 위치기반 검색지 최대 검색개수 50개로 제한 및 검색 장소 랜덤으로 검색 하도록 쿼리 수정<br>
> [refactor/search] 현재 위치기반 장소 검색기능 수정

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/Repository/SavedRepository.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
유저가 저장한 관광지 삭제 API 추가 userNumber, ContentID 를 통해 삭제 가능
> [feat] 관광지 저장 삭제 기능 추가

- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinReq.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
validJoin을 UserJoinReq에서 분리해 UserService로 이동했습니다.
또한, 로직을 isBlank, isValidList로 분리했습니다.
> fix: validJoin 분리

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Disability/UserDisabilityRepository.java
- BEF/src/main/java/com/example/BEF/TripType/UserTripTypeRepository.java
- BEF/src/main/java/com/example/BEF/User/DTO/UserJoinReq.java
- BEF/src/main/java/com/example/BEF/User/Service/UserService.java
유저 장애 유형, 여행 타입을 기존의 유저 정보가 아닌 유저-장애유형, 유저-여행타입 정보에서 추출
> [Fix] Quick 코스 생성

- BEF/src/main/java/com/example/BEF/Course/Controller/CourseController.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseInfoRes.java
- BEF/src/main/java/com/example/BEF/Course/DTO/CourseLocationRes.java
- BEF/src/main/java/com/example/BEF/Course/Domain/CourseDisability.java
- BEF/src/main/java/com/example/BEF/Course/Repository/CourseDisabilityRepository.java
- BEF/src/main/java/com/example/BEF/Course/Repository/CourseRepository.java
- BEF/src/main/java/com/example/BEF/Course/Service/CourseService.java
코스 기본 정보를 추가했습니다.
- 코스 번호, 이름
- 지역
- 기간
- 코스 장애 정보
- CourseInfoRes
- 일자별 관광지 리스트
> [Fix] 코스 관련 API 응답 수정

- BEF/src/main/java/com/example/BEF/Config/WebConfig.java
> [feat] CORS 설정 추가
